/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as ArtIndexRouteImport } from './routes/art.index'
import { Route as ArtBoutiqueRouteImport } from './routes/art.boutique'
import { Route as ArtCheckoutRouteImport } from './routes/art.checkout'
import { Route as ArtPanierRouteImport } from './routes/art.panier'
import { Route as ArtisteIndexRouteImport } from './routes/artiste.index'
import { Route as ArtisteCommandesRouteImport } from './routes/artiste.commandes'
import { Route as ArtisteVitrineRouteImport } from './routes/artiste.vitrine'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as CultureIndexRouteImport } from './routes/culture.index'
import { Route as EvenementsIndexRouteImport } from './routes/evenements.index'
import { Route as EvenementsSlugRouteImport } from './routes/evenements.$slug'
import { Route as ProfilIndexRouteImport } from './routes/profil.index'
import { Route as ProfilCommandesRouteImport } from './routes/profil.commandes'
import { Route as ProfilDetailsRouteImport } from './routes/profil.details'
import { Route as ProfilFavorisRouteImport } from './routes/profil.favoris'
import { Route as ProfilMotDePasseRouteImport } from './routes/profil.mot-de-passe'
import { Route as TourismeIndexRouteImport } from './routes/tourisme.index'
import { Route as TourismeCarteRouteImport } from './routes/tourisme.carte'
import { Route as TourismeGastronomieRouteImport } from './routes/tourisme.gastronomie'
import { Route as TourismeReservationRouteImport } from './routes/tourisme.reservation'
import { Route as VisiteSlugRouteImport } from './routes/visite.$slug'
import { Route as ArtArtistesSlugRouteImport } from './routes/art.artistes.$slug'
import { Route as ArtCommandeErreurRouteImport } from './routes/art.commande.erreur'
import { Route as ArtCommandeSuccesRouteImport } from './routes/art.commande.succes'
import { Route as ArtOeuvresSlugRouteImport } from './routes/art.oeuvres.$slug'
import { Route as CultureDossiersSlugRouteImport } from './routes/culture.dossiers.$slug'
import { Route as CultureMuseesSlugRouteImport } from './routes/culture.musees.$slug'
import { Route as CultureRoyaumesSlugRouteImport } from './routes/culture.royaumes.$slug'
import { Route as TourismeGastronomieIndexRouteImport } from './routes/tourisme.gastronomie.index'
import { Route as TourismeGastronomieSlugRouteImport } from './routes/tourisme.gastronomie.$slug'
import { Route as TourismeSitesSlugRouteImport } from './routes/tourisme.sites.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIndexRoute = ArtIndexRouteImport.update({
  id: '/art/',
  path: '/art/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtBoutiqueRoute = ArtBoutiqueRouteImport.update({
  id: '/art/boutique',
  path: '/art/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtCheckoutRoute = ArtCheckoutRouteImport.update({
  id: '/art/checkout',
  path: '/art/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtPanierRoute = ArtPanierRouteImport.update({
  id: '/art/panier',
  path: '/art/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisteIndexRoute = ArtisteIndexRouteImport.update({
  id: '/artiste/',
  path: '/artiste/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisteCommandesRoute = ArtisteCommandesRouteImport.update({
  id: '/artiste/commandes',
  path: '/artiste/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisteVitrineRoute = ArtisteVitrineRouteImport.update({
  id: '/artiste/vitrine',
  path: '/artiste/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureIndexRoute = CultureIndexRouteImport.update({
  id: '/culture/',
  path: '/culture/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsIndexRoute = EvenementsIndexRouteImport.update({
  id: '/evenements/',
  path: '/evenements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsSlugRoute = EvenementsSlugRouteImport.update({
  id: '/evenements/$slug',
  path: '/evenements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilCommandesRoute = ProfilCommandesRouteImport.update({
  id: '/profil/commandes',
  path: '/profil/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilDetailsRoute = ProfilDetailsRouteImport.update({
  id: '/profil/details',
  path: '/profil/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilFavorisRoute = ProfilFavorisRouteImport.update({
  id: '/profil/favoris',
  path: '/profil/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilMotDePasseRoute = ProfilMotDePasseRouteImport.update({
  id: '/profil/mot-de-passe',
  path: '/profil/mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismeIndexRoute = TourismeIndexRouteImport.update({
  id: '/tourisme/',
  path: '/tourisme/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismeCarteRoute = TourismeCarteRouteImport.update({
  id: '/tourisme/carte',
  path: '/tourisme/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismeGastronomieRoute = TourismeGastronomieRouteImport.update({
  id: '/tourisme/gastronomie',
  path: '/tourisme/gastronomie',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismeReservationRoute = TourismeReservationRouteImport.update({
  id: '/tourisme/reservation',
  path: '/tourisme/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiteSlugRoute = VisiteSlugRouteImport.update({
  id: '/visite/$slug',
  path: '/visite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtArtistesSlugRoute = ArtArtistesSlugRouteImport.update({
  id: '/art/artistes/$slug',
  path: '/art/artistes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtCommandeErreurRoute = ArtCommandeErreurRouteImport.update({
  id: '/art/commande/erreur',
  path: '/art/commande/erreur',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtCommandeSuccesRoute = ArtCommandeSuccesRouteImport.update({
  id: '/art/commande/succes',
  path: '/art/commande/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtOeuvresSlugRoute = ArtOeuvresSlugRouteImport.update({
  id: '/art/oeuvres/$slug',
  path: '/art/oeuvres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureDossiersSlugRoute = CultureDossiersSlugRouteImport.update({
  id: '/culture/dossiers/$slug',
  path: '/culture/dossiers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureMuseesSlugRoute = CultureMuseesSlugRouteImport.update({
  id: '/culture/musees/$slug',
  path: '/culture/musees/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoyaumesSlugRoute = CultureRoyaumesSlugRouteImport.update({
  id: '/culture/royaumes/$slug',
  path: '/culture/royaumes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismeGastronomieIndexRoute =
  TourismeGastronomieIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TourismeGastronomieRoute,
  } as any)
const TourismeGastronomieSlugRoute = TourismeGastronomieSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TourismeGastronomieRoute,
} as any)
const TourismeSitesSlugRoute = TourismeSitesSlugRouteImport.update({
  id: '/tourisme/sites/$slug',
  path: '/tourisme/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/art/boutique': typeof ArtBoutiqueRoute
  '/art/checkout': typeof ArtCheckoutRoute
  '/art/panier': typeof ArtPanierRoute
  '/artiste/commandes': typeof ArtisteCommandesRoute
  '/artiste/vitrine': typeof ArtisteVitrineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/profil/commandes': typeof ProfilCommandesRoute
  '/profil/details': typeof ProfilDetailsRoute
  '/profil/favoris': typeof ProfilFavorisRoute
  '/profil/mot-de-passe': typeof ProfilMotDePasseRoute
  '/tourisme/carte': typeof TourismeCarteRoute
  '/tourisme/gastronomie': typeof TourismeGastronomieRouteWithChildren
  '/tourisme/reservation': typeof TourismeReservationRoute
  '/visite/$slug': typeof VisiteSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/art/': typeof ArtIndexRoute
  '/artiste/': typeof ArtisteIndexRoute
  '/culture/': typeof CultureIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/tourisme/': typeof TourismeIndexRoute
  '/art/artistes/$slug': typeof ArtArtistesSlugRoute
  '/art/commande/erreur': typeof ArtCommandeErreurRoute
  '/art/commande/succes': typeof ArtCommandeSuccesRoute
  '/art/oeuvres/$slug': typeof ArtOeuvresSlugRoute
  '/culture/dossiers/$slug': typeof CultureDossiersSlugRoute
  '/culture/musees/$slug': typeof CultureMuseesSlugRoute
  '/culture/royaumes/$slug': typeof CultureRoyaumesSlugRoute
  '/tourisme/gastronomie/$slug': typeof TourismeGastronomieSlugRoute
  '/tourisme/sites/$slug': typeof TourismeSitesSlugRoute
  '/tourisme/gastronomie/': typeof TourismeGastronomieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/art/boutique': typeof ArtBoutiqueRoute
  '/art/checkout': typeof ArtCheckoutRoute
  '/art/panier': typeof ArtPanierRoute
  '/artiste/commandes': typeof ArtisteCommandesRoute
  '/artiste/vitrine': typeof ArtisteVitrineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/profil/commandes': typeof ProfilCommandesRoute
  '/profil/details': typeof ProfilDetailsRoute
  '/profil/favoris': typeof ProfilFavorisRoute
  '/profil/mot-de-passe': typeof ProfilMotDePasseRoute
  '/tourisme/carte': typeof TourismeCarteRoute
  '/tourisme/reservation': typeof TourismeReservationRoute
  '/visite/$slug': typeof VisiteSlugRoute
  '/admin': typeof AdminIndexRoute
  '/art': typeof ArtIndexRoute
  '/artiste': typeof ArtisteIndexRoute
  '/culture': typeof CultureIndexRoute
  '/evenements': typeof EvenementsIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/tourisme': typeof TourismeIndexRoute
  '/art/artistes/$slug': typeof ArtArtistesSlugRoute
  '/art/commande/erreur': typeof ArtCommandeErreurRoute
  '/art/commande/succes': typeof ArtCommandeSuccesRoute
  '/art/oeuvres/$slug': typeof ArtOeuvresSlugRoute
  '/culture/dossiers/$slug': typeof CultureDossiersSlugRoute
  '/culture/musees/$slug': typeof CultureMuseesSlugRoute
  '/culture/royaumes/$slug': typeof CultureRoyaumesSlugRoute
  '/tourisme/gastronomie/$slug': typeof TourismeGastronomieSlugRoute
  '/tourisme/sites/$slug': typeof TourismeSitesSlugRoute
  '/tourisme/gastronomie': typeof TourismeGastronomieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/art/boutique': typeof ArtBoutiqueRoute
  '/art/checkout': typeof ArtCheckoutRoute
  '/art/panier': typeof ArtPanierRoute
  '/artiste/commandes': typeof ArtisteCommandesRoute
  '/artiste/vitrine': typeof ArtisteVitrineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/evenements/$slug': typeof EvenementsSlugRoute
  '/profil/commandes': typeof ProfilCommandesRoute
  '/profil/details': typeof ProfilDetailsRoute
  '/profil/favoris': typeof ProfilFavorisRoute
  '/profil/mot-de-passe': typeof ProfilMotDePasseRoute
  '/tourisme/carte': typeof TourismeCarteRoute
  '/tourisme/gastronomie': typeof TourismeGastronomieRouteWithChildren
  '/tourisme/reservation': typeof TourismeReservationRoute
  '/visite/$slug': typeof VisiteSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/art/': typeof ArtIndexRoute
  '/artiste/': typeof ArtisteIndexRoute
  '/culture/': typeof CultureIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/tourisme/': typeof TourismeIndexRoute
  '/art/artistes/$slug': typeof ArtArtistesSlugRoute
  '/art/commande/erreur': typeof ArtCommandeErreurRoute
  '/art/commande/succes': typeof ArtCommandeSuccesRoute
  '/art/oeuvres/$slug': typeof ArtOeuvresSlugRoute
  '/culture/dossiers/$slug': typeof CultureDossiersSlugRoute
  '/culture/musees/$slug': typeof CultureMuseesSlugRoute
  '/culture/royaumes/$slug': typeof CultureRoyaumesSlugRoute
  '/tourisme/gastronomie/$slug': typeof TourismeGastronomieSlugRoute
  '/tourisme/sites/$slug': typeof TourismeSitesSlugRoute
  '/tourisme/gastronomie/': typeof TourismeGastronomieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/assistant'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/admin/moderation'
    | '/art/boutique'
    | '/art/checkout'
    | '/art/panier'
    | '/artiste/commandes'
    | '/artiste/vitrine'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/update-password'
    | '/evenements/$slug'
    | '/profil/commandes'
    | '/profil/details'
    | '/profil/favoris'
    | '/profil/mot-de-passe'
    | '/tourisme/carte'
    | '/tourisme/gastronomie'
    | '/tourisme/reservation'
    | '/visite/$slug'
    | '/admin/'
    | '/art/'
    | '/artiste/'
    | '/culture/'
    | '/evenements/'
    | '/profil/'
    | '/tourisme/'
    | '/art/artistes/$slug'
    | '/art/commande/erreur'
    | '/art/commande/succes'
    | '/art/oeuvres/$slug'
    | '/culture/dossiers/$slug'
    | '/culture/musees/$slug'
    | '/culture/royaumes/$slug'
    | '/tourisme/gastronomie/$slug'
    | '/tourisme/sites/$slug'
    | '/tourisme/gastronomie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/assistant'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/admin/moderation'
    | '/art/boutique'
    | '/art/checkout'
    | '/art/panier'
    | '/artiste/commandes'
    | '/artiste/vitrine'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/update-password'
    | '/evenements/$slug'
    | '/profil/commandes'
    | '/profil/details'
    | '/profil/favoris'
    | '/profil/mot-de-passe'
    | '/tourisme/carte'
    | '/tourisme/reservation'
    | '/visite/$slug'
    | '/admin'
    | '/art'
    | '/artiste'
    | '/culture'
    | '/evenements'
    | '/profil'
    | '/tourisme'
    | '/art/artistes/$slug'
    | '/art/commande/erreur'
    | '/art/commande/succes'
    | '/art/oeuvres/$slug'
    | '/culture/dossiers/$slug'
    | '/culture/musees/$slug'
    | '/culture/royaumes/$slug'
    | '/tourisme/gastronomie/$slug'
    | '/tourisme/sites/$slug'
    | '/tourisme/gastronomie'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/assistant'
    | '/contact'
    | '/faq'
    | '/legal'
    | '/admin/moderation'
    | '/art/boutique'
    | '/art/checkout'
    | '/art/panier'
    | '/artiste/commandes'
    | '/artiste/vitrine'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/update-password'
    | '/evenements/$slug'
    | '/profil/commandes'
    | '/profil/details'
    | '/profil/favoris'
    | '/profil/mot-de-passe'
    | '/tourisme/carte'
    | '/tourisme/gastronomie'
    | '/tourisme/reservation'
    | '/visite/$slug'
    | '/admin/'
    | '/art/'
    | '/artiste/'
    | '/culture/'
    | '/evenements/'
    | '/profil/'
    | '/tourisme/'
    | '/art/artistes/$slug'
    | '/art/commande/erreur'
    | '/art/commande/succes'
    | '/art/oeuvres/$slug'
    | '/culture/dossiers/$slug'
    | '/culture/musees/$slug'
    | '/culture/royaumes/$slug'
    | '/tourisme/gastronomie/$slug'
    | '/tourisme/sites/$slug'
    | '/tourisme/gastronomie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AssistantRoute: typeof AssistantRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  AdminModerationRoute: typeof AdminModerationRoute
  ArtBoutiqueRoute: typeof ArtBoutiqueRoute
  ArtCheckoutRoute: typeof ArtCheckoutRoute
  ArtPanierRoute: typeof ArtPanierRoute
  ArtisteCommandesRoute: typeof ArtisteCommandesRoute
  ArtisteVitrineRoute: typeof ArtisteVitrineRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  EvenementsSlugRoute: typeof EvenementsSlugRoute
  ProfilCommandesRoute: typeof ProfilCommandesRoute
  ProfilDetailsRoute: typeof ProfilDetailsRoute
  ProfilFavorisRoute: typeof ProfilFavorisRoute
  ProfilMotDePasseRoute: typeof ProfilMotDePasseRoute
  TourismeCarteRoute: typeof TourismeCarteRoute
  TourismeGastronomieRoute: typeof TourismeGastronomieRouteWithChildren
  TourismeReservationRoute: typeof TourismeReservationRoute
  VisiteSlugRoute: typeof VisiteSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArtIndexRoute: typeof ArtIndexRoute
  ArtisteIndexRoute: typeof ArtisteIndexRoute
  CultureIndexRoute: typeof CultureIndexRoute
  EvenementsIndexRoute: typeof EvenementsIndexRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
  TourismeIndexRoute: typeof TourismeIndexRoute
  ArtArtistesSlugRoute: typeof ArtArtistesSlugRoute
  ArtCommandeErreurRoute: typeof ArtCommandeErreurRoute
  ArtCommandeSuccesRoute: typeof ArtCommandeSuccesRoute
  ArtOeuvresSlugRoute: typeof ArtOeuvresSlugRoute
  CultureDossiersSlugRoute: typeof CultureDossiersSlugRoute
  CultureMuseesSlugRoute: typeof CultureMuseesSlugRoute
  CultureRoyaumesSlugRoute: typeof CultureRoyaumesSlugRoute
  TourismeSitesSlugRoute: typeof TourismeSitesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/': {
      id: '/art/'
      path: '/art'
      fullPath: '/art/'
      preLoaderRoute: typeof ArtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/boutique': {
      id: '/art/boutique'
      path: '/art/boutique'
      fullPath: '/art/boutique'
      preLoaderRoute: typeof ArtBoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/checkout': {
      id: '/art/checkout'
      path: '/art/checkout'
      fullPath: '/art/checkout'
      preLoaderRoute: typeof ArtCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/panier': {
      id: '/art/panier'
      path: '/art/panier'
      fullPath: '/art/panier'
      preLoaderRoute: typeof ArtPanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artiste/': {
      id: '/artiste/'
      path: '/artiste'
      fullPath: '/artiste/'
      preLoaderRoute: typeof ArtisteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artiste/commandes': {
      id: '/artiste/commandes'
      path: '/artiste/commandes'
      fullPath: '/artiste/commandes'
      preLoaderRoute: typeof ArtisteCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artiste/vitrine': {
      id: '/artiste/vitrine'
      path: '/artiste/vitrine'
      fullPath: '/artiste/vitrine'
      preLoaderRoute: typeof ArtisteVitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture/': {
      id: '/culture/'
      path: '/culture'
      fullPath: '/culture/'
      preLoaderRoute: typeof CultureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements/': {
      id: '/evenements/'
      path: '/evenements'
      fullPath: '/evenements/'
      preLoaderRoute: typeof EvenementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements/$slug': {
      id: '/evenements/$slug'
      path: '/evenements/$slug'
      fullPath: '/evenements/$slug'
      preLoaderRoute: typeof EvenementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/commandes': {
      id: '/profil/commandes'
      path: '/profil/commandes'
      fullPath: '/profil/commandes'
      preLoaderRoute: typeof ProfilCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/details': {
      id: '/profil/details'
      path: '/profil/details'
      fullPath: '/profil/details'
      preLoaderRoute: typeof ProfilDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/favoris': {
      id: '/profil/favoris'
      path: '/profil/favoris'
      fullPath: '/profil/favoris'
      preLoaderRoute: typeof ProfilFavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/mot-de-passe': {
      id: '/profil/mot-de-passe'
      path: '/profil/mot-de-passe'
      fullPath: '/profil/mot-de-passe'
      preLoaderRoute: typeof ProfilMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourisme/': {
      id: '/tourisme/'
      path: '/tourisme'
      fullPath: '/tourisme/'
      preLoaderRoute: typeof TourismeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourisme/carte': {
      id: '/tourisme/carte'
      path: '/tourisme/carte'
      fullPath: '/tourisme/carte'
      preLoaderRoute: typeof TourismeCarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourisme/gastronomie': {
      id: '/tourisme/gastronomie'
      path: '/tourisme/gastronomie'
      fullPath: '/tourisme/gastronomie'
      preLoaderRoute: typeof TourismeGastronomieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourisme/reservation': {
      id: '/tourisme/reservation'
      path: '/tourisme/reservation'
      fullPath: '/tourisme/reservation'
      preLoaderRoute: typeof TourismeReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visite/$slug': {
      id: '/visite/$slug'
      path: '/visite/$slug'
      fullPath: '/visite/$slug'
      preLoaderRoute: typeof VisiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/artistes/$slug': {
      id: '/art/artistes/$slug'
      path: '/art/artistes/$slug'
      fullPath: '/art/artistes/$slug'
      preLoaderRoute: typeof ArtArtistesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/commande/erreur': {
      id: '/art/commande/erreur'
      path: '/art/commande/erreur'
      fullPath: '/art/commande/erreur'
      preLoaderRoute: typeof ArtCommandeErreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/commande/succes': {
      id: '/art/commande/succes'
      path: '/art/commande/succes'
      fullPath: '/art/commande/succes'
      preLoaderRoute: typeof ArtCommandeSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/oeuvres/$slug': {
      id: '/art/oeuvres/$slug'
      path: '/art/oeuvres/$slug'
      fullPath: '/art/oeuvres/$slug'
      preLoaderRoute: typeof ArtOeuvresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture/dossiers/$slug': {
      id: '/culture/dossiers/$slug'
      path: '/culture/dossiers/$slug'
      fullPath: '/culture/dossiers/$slug'
      preLoaderRoute: typeof CultureDossiersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture/musees/$slug': {
      id: '/culture/musees/$slug'
      path: '/culture/musees/$slug'
      fullPath: '/culture/musees/$slug'
      preLoaderRoute: typeof CultureMuseesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture/royaumes/$slug': {
      id: '/culture/royaumes/$slug'
      path: '/culture/royaumes/$slug'
      fullPath: '/culture/royaumes/$slug'
      preLoaderRoute: typeof CultureRoyaumesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourisme/gastronomie/': {
      id: '/tourisme/gastronomie/'
      path: '/'
      fullPath: '/tourisme/gastronomie/'
      preLoaderRoute: typeof TourismeGastronomieIndexRouteImport
      parentRoute: typeof TourismeGastronomieRoute
    }
    '/tourisme/gastronomie/$slug': {
      id: '/tourisme/gastronomie/$slug'
      path: '/$slug'
      fullPath: '/tourisme/gastronomie/$slug'
      preLoaderRoute: typeof TourismeGastronomieSlugRouteImport
      parentRoute: typeof TourismeGastronomieRoute
    }
    '/tourisme/sites/$slug': {
      id: '/tourisme/sites/$slug'
      path: '/tourisme/sites/$slug'
      fullPath: '/tourisme/sites/$slug'
      preLoaderRoute: typeof TourismeSitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TourismeGastronomieRouteChildren {
  TourismeGastronomieSlugRoute: typeof TourismeGastronomieSlugRoute
  TourismeGastronomieIndexRoute: typeof TourismeGastronomieIndexRoute
}

const TourismeGastronomieRouteChildren: TourismeGastronomieRouteChildren = {
  TourismeGastronomieSlugRoute: TourismeGastronomieSlugRoute,
  TourismeGastronomieIndexRoute: TourismeGastronomieIndexRoute,
}

const TourismeGastronomieRouteWithChildren =
  TourismeGastronomieRoute._addFileChildren(TourismeGastronomieRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AssistantRoute: AssistantRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  AdminModerationRoute: AdminModerationRoute,
  ArtBoutiqueRoute: ArtBoutiqueRoute,
  ArtCheckoutRoute: ArtCheckoutRoute,
  ArtPanierRoute: ArtPanierRoute,
  ArtisteCommandesRoute: ArtisteCommandesRoute,
  ArtisteVitrineRoute: ArtisteVitrineRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  EvenementsSlugRoute: EvenementsSlugRoute,
  ProfilCommandesRoute: ProfilCommandesRoute,
  ProfilDetailsRoute: ProfilDetailsRoute,
  ProfilFavorisRoute: ProfilFavorisRoute,
  ProfilMotDePasseRoute: ProfilMotDePasseRoute,
  TourismeCarteRoute: TourismeCarteRoute,
  TourismeGastronomieRoute: TourismeGastronomieRouteWithChildren,
  TourismeReservationRoute: TourismeReservationRoute,
  VisiteSlugRoute: VisiteSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArtIndexRoute: ArtIndexRoute,
  ArtisteIndexRoute: ArtisteIndexRoute,
  CultureIndexRoute: CultureIndexRoute,
  EvenementsIndexRoute: EvenementsIndexRoute,
  ProfilIndexRoute: ProfilIndexRoute,
  TourismeIndexRoute: TourismeIndexRoute,
  ArtArtistesSlugRoute: ArtArtistesSlugRoute,
  ArtCommandeErreurRoute: ArtCommandeErreurRoute,
  ArtCommandeSuccesRoute: ArtCommandeSuccesRoute,
  ArtOeuvresSlugRoute: ArtOeuvresSlugRoute,
  CultureDossiersSlugRoute: CultureDossiersSlugRoute,
  CultureMuseesSlugRoute: CultureMuseesSlugRoute,
  CultureRoyaumesSlugRoute: CultureRoyaumesSlugRoute,
  TourismeSitesSlugRoute: TourismeSitesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
